name: Puppeteer Visit HTML
on:
  schedule:
    - cron: '30 8 * * *'  # 每天，五个参数时：分 时 日 月 周，也可六个或七个参数
  workflow_dispatch:

jobs:
  visit:
    runs-on: ubuntu-latest
    timeout-minutes: 10   # 防止超时
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev  # 解决 Chromium 依赖问题
          npm install puppeteer@latest

      - name: Run Puppeteer
        run: |
          node <<EOF
          const puppeteer = require('puppeteer');
          (async () => {
            try {
              const browser = await puppeteer.launch({
                headless: 'new',
                args: ['--no-sandbox'] 
              });
              const page = await browser.newPage();
              
              await page.goto('https://linmsh-real.github.io/kzz-web/');
              
              
              await page.screenshot({ path: 'screenshot.png' });
              console.log('截图成功！');
              
              await browser.close();
            } catch (error) {
              console.error('Puppeteer 错误:', error);
              process.exit(1);
            }
          })();
          EOF

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4  # 使用 v4 版本
        if: always()  # 即使失败也上传日志
        #uses: actions/upload-artifact@v3
        with:
          name: puppeteer-screenshot
          path: screenshot.png
